version: "3.9"

# コンテナの設定
services:
  web:
    # image: go-clean-arch
    container_name: go_api
    build:
      context: .
      dockerfile: Dockerfile

    # ホスト側のフォルダをマウントする
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    depends_on:
      - mysql
    ports:
      - "8080:8080"

  mysql:
    image: mysql:8.3
    container_name: go_clean_arch_mysql
    command: mysqld --user=root
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=go_clean_arch
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
      # タイムゾーン
      - TZ=Asia/Tokyo
    volumes:
      - ./mysql.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
