version: "3.9"

# コンテナの設定
services:
  web:
    image: go-clean-arch
    container_name: go_api
    # build:
    #   context: .
    #   dockerfile: ./app/Dockerfile

    # ホスト側のフォルダをマウントする
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    depends_on:
      - mysql
    ports:
      - 9090:9090

  mysql:
    image: mysql:8.3
    container_name: go_clean_arch_mysql
    command: mysqld --user=root
    # volumes:
    #   - ./article.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$DATABASE_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      # タイムゾーン
      - TZ=Asia/Tokyo
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
